# Generated by Django 5.2 on 2025-05-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's phone number is verified.",
                verbose_name="phone verified",
            ),
        ),
    ]
