# Generated by Django 5.2 on 2025-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_phone_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user is subscribed to notifications.",
                verbose_name="subscribed",
            ),
        ),
    ]
