# Generated by Django 5.2 on 2025-04-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bills_mock_django",
            fields=[
                (
                    "bill_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.CharField()),
                ("title", models.CharField()),
                ("summary", models.CharField()),
                ("status", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="users_mock_django",
            fields=[
                (
                    "user_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("password", models.CharField()),
                ("phone", models.CharField()),
                ("zip", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="actions_mock_django",
            fields=[
                (
                    "action_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.CharField()),
                ("date", models.DateTimeField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bills_mock_django",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sponsors_mock_django",
            fields=[
                (
                    "id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("sponsor_id", models.CharField()),
                ("sponsor_name", models.CharField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bills_mock_django",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="topics_mock_django",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bills_mock_django",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="favorites_mock_django",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bills_mock_django",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.users_mock_django",
                    ),
                ),
            ],
        ),
    ]
