# Generated by Django 5.2 on 2025-04-22 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actions_mock_django",
            table="actions_mock_django",
        ),
        migrations.AlterModelTable(
            name="bills_mock_django",
            table="bills_mock_django",
        ),
        migrations.AlterModelTable(
            name="favorites_mock_django",
            table="favorites_mock_django",
        ),
        migrations.AlterModelTable(
            name="sponsors_mock_django",
            table="sponsors_mock_django",
        ),
        migrations.AlterModelTable(
            name="topics_mock_django",
            table="topics_mock_django",
        ),
        migrations.AlterModelTable(
            name="users_mock_django",
            table="users_mock_django",
        ),
    ]
