# Generated by Django 5.2 on 2025-04-22 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_actions_mock_django_table_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="actions_mock_django",
            new_name="ActionsMockDjango",
        ),
        migrations.RenameModel(
            old_name="bills_mock_django",
            new_name="BillsMockDjango",
        ),
        migrations.RenameModel(
            old_name="favorites_mock_django",
            new_name="FavoritesMockDjango",
        ),
        migrations.RenameModel(
            old_name="sponsors_mock_django",
            new_name="SponsorsMockDjango",
        ),
        migrations.RenameModel(
            old_name="topics_mock_django",
            new_name="TopicsMockDjango",
        ),
        migrations.RenameModel(
            old_name="users_mock_django",
            new_name="UsersMockDjango",
        ),
        migrations.AlterUniqueTogether(
            name="favoritesmockdjango",
            unique_together={("user_id", "bill_id")},
        ),
    ]
