# Generated by Django 5.2 on 2025-04-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_actions_mock_django_actionsmockdjango_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritesmockdjango",
            name="bill_id",
            field=models.ForeignKey(
                db_column="bill_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.billsmockdjango",
            ),
        ),
        migrations.AlterField(
            model_name="favoritesmockdjango",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.usersmockdjango",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorsmockdjango",
            name="bill_id",
            field=models.ForeignKey(
                db_column="bill_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.billsmockdjango",
            ),
        ),
        migrations.AlterField(
            model_name="topicsmockdjango",
            name="bill_id",
            field=models.ForeignKey(
                db_column="bill_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.billsmockdjango",
            ),
        ),
    ]
