# Generated by Django 5.2 on 2025-04-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_favoritesmockdjango_bill_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionsmockdjango",
            name="bill_id",
            field=models.ForeignKey(
                db_column="bill_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.billsmockdjango",
            ),
        ),
    ]
