# Generated by Django 5.2 on 2025-04-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_actionsmockdjango_bill_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritesmockdjango",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="favoritesmockdjango",
            table=None,
        ),
    ]
