# Generated by Django 5.2 on 2025-04-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_favoritesmockdjango_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="favoritesmockdjango",
            table="favorites_mock_django",
        ),
    ]
