# Generated by Django 5.2 on 2025-04-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_favoritesmockdjango_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritesmockdjango",
            unique_together={("user_id", "bill_id")},
        ),
    ]
