# Generated by Django 5.2 on 2025-04-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_favoritesmockdjango_unique_together"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actionsmockdjango",
            table="actions_mock",
        ),
        migrations.AlterModelTable(
            name="billsmockdjango",
            table="bills_mock",
        ),
        migrations.AlterModelTable(
            name="favoritesmockdjango",
            table="favorites_mock",
        ),
        migrations.AlterModelTable(
            name="sponsorsmockdjango",
            table="sponsors_mock",
        ),
        migrations.AlterModelTable(
            name="topicsmockdjango",
            table="topics_mock",
        ),
        migrations.AlterModelTable(
            name="usersmockdjango",
            table="users_mock",
        ),
    ]
