# Generated by Django 5.2 on 2025-04-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_actionsmockdjango_table_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActionsMockDjango",
            new_name="ActionsMock",
        ),
        migrations.RenameModel(
            old_name="BillsMockDjango",
            new_name="BillsMock",
        ),
        migrations.RenameModel(
            old_name="FavoritesMockDjango",
            new_name="FavoritesMock",
        ),
        migrations.RenameModel(
            old_name="SponsorsMockDjango",
            new_name="SponsorsMock",
        ),
        migrations.RenameModel(
            old_name="TopicsMockDjango",
            new_name="TopicsMock",
        ),
        migrations.RenameModel(
            old_name="UsersMockDjango",
            new_name="UsersMock",
        ),
    ]
