# Generated by Django 5.2 on 2025-04-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_actionsmockdjango_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillsTable",
            fields=[
                (
                    "bill_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.CharField()),
                ("title", models.CharField()),
                ("summary", models.CharField()),
                ("status", models.CharField()),
            ],
            options={
                "db_table": "bills_table",
            },
        ),
        migrations.CreateModel(
            name="UsersTable",
            fields=[
                (
                    "user_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("password", models.CharField()),
                ("phone", models.CharField()),
                ("zip", models.CharField()),
            ],
            options={
                "db_table": "users_table",
            },
        ),
        migrations.CreateModel(
            name="ActionsTable",
            fields=[
                (
                    "action_id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.CharField()),
                ("date", models.DateTimeField()),
                ("category", models.CharField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
            ],
            options={
                "db_table": "actions_table",
            },
        ),
        migrations.CreateModel(
            name="SponsorsTable",
            fields=[
                (
                    "id",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("sponsor_id", models.CharField()),
                ("sponsor_name", models.CharField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
            ],
            options={
                "db_table": "sponsors_table",
            },
        ),
        migrations.CreateModel(
            name="TopicsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
            ],
            options={
                "db_table": "topics_table",
            },
        ),
        migrations.CreateModel(
            name="FavoritesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userstable",
                    ),
                ),
            ],
            options={
                "db_table": "favorites_table",
                "unique_together": {("user_id", "bill_id")},
            },
        ),
    ]
