# Generated by Django 5.2 on 2025-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sponsorstable_party_sponsorstable_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionstable",
            name="chamber",
            field=models.CharField(default=None, null=True),
        ),
    ]
