# Generated by Django 5.2 on 2025-05-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_favoritestable_user_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritesmockdjango",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="favoritesmockdjango",
            name="bill_id",
        ),
        migrations.RemoveField(
            model_name="favoritesmockdjango",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="UsersTable",
        ),
        migrations.DeleteModel(
            name="FavoritesMockDjango",
        ),
        migrations.DeleteModel(
            name="UsersMockDjango",
        ),
    ]
