# Generated by Django 5.2 on 2025-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_billsmockdjango_session_billsmockdjango_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billsmockdjango",
            name="session",
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="billsmockdjango",
            name="state",
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="billstable",
            name="session",
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="billstable",
            name="state",
            field=models.CharField(default=None, null=True),
        ),
    ]
