# Generated by Django 5.2 on 2025-05-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_billsmockdjango_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billsmockdjango",
            name="session",
            field=models.CharField(null=True),
        ),
    ]
