# Generated by Django 5.2 on 2025-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_billsmockdjango_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billsmockdjango",
            name="session",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="billsmockdjango",
            name="state",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="billstable",
            name="session",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="billstable",
            name="state",
            field=models.CharField(default="", null=True),
        ),
    ]
