# Generated by Django 5.2 on 2025-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_billsmockdjango_session_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billsmockdjango",
            old_name="session",
            new_name="bill_session",
        ),
        migrations.RemoveField(
            model_name="billstable",
            name="session",
        ),
        migrations.AddField(
            model_name="billstable",
            name="bill_session",
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="billstable",
            name="state",
            field=models.CharField(default=None, null=True),
        ),
    ]
