# Generated by Django 5.2 on 2025-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_session_billsmockdjango_bill_session_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billsmockdjango",
            old_name="bill_session",
            new_name="session",
        ),
        migrations.RenameField(
            model_name="billstable",
            old_name="bill_session",
            new_name="session",
        ),
    ]
