# Generated by Django 5.2 on 2025-05-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_billsmockdjango_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionstable",
            name="action_id",
            field=models.CharField(
                db_column="action_id", primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actionstable",
            unique_together={("action_id", "bill_id")},
        ),
        migrations.CreateModel(
            name="UpdatesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField()),
                ("date", models.DateTimeField()),
                ("category", models.CharField(null=True)),
                ("chamber", models.CharField()),
                (
                    "action_id",
                    models.ForeignKey(
                        db_column="action_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.actionstable",
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
            ],
            options={
                "db_table": "updates_table",
                "unique_together": {("action_id", "bill_id")},
            },
        ),
    ]
