# Generated by Django 5.2 on 2025-05-14 03:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_billsmockdjango_session_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionstable",
            name="action_id",
            field=models.CharField(
                db_column="action_id", primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="UserNotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_notifications", models.IntegerField()),
                (
                    "bills_to_notify",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), default=list, size=None
                    ),
                ),
                ("is_notified", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notification_queue",
            },
        ),
        migrations.CreateModel(
            name="UpdatesMockDjango",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField()),
                ("date", models.DateTimeField()),
                ("category", models.CharField(null=True)),
                ("chamber", models.CharField()),
                (
                    "action_id",
                    models.ForeignKey(
                        db_column="action_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.actionsmockdjango",
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billsmockdjango",
                    ),
                ),
            ],
            options={
                "db_table": "updates_mock",
                "unique_together": {("action_id", "bill_id")},
            },
        ),
        migrations.CreateModel(
            name="UpdatesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField()),
                ("date", models.DateTimeField()),
                ("category", models.CharField(null=True)),
                ("chamber", models.CharField()),
                (
                    "action_id",
                    models.ForeignKey(
                        db_column="action_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.actionstable",
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        db_column="bill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.billstable",
                    ),
                ),
            ],
            options={
                "db_table": "updates_table",
                "unique_together": {("action_id", "bill_id")},
            },
        ),
    ]
