# Generated by Django 5.2 on 2025-05-13 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_actionstable_action_id_and_more"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name="UpdatesMockDjango",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("description", models.CharField()),
        #         ("date", models.DateTimeField()),
        #         ("category", models.CharField(null=True)),
        #         ("chamber", models.CharField()),
        #         (
        #             "action_id",
        #             models.ForeignKey(
        #                 db_column="action_id",
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="core.actionsmockdjango",
        #             ),
        #         ),
        #         (
        #             "bill_id",
        #             models.ForeignKey(
        #                 db_column="bill_id",
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="core.billsmockdjango",
        #             ),
        #         ),
        #     ],
        #     options={
        #         "db_table": "updates_mock",
        #         "unique_together": {("action_id", "bill_id")},
        #     },
        # ),
    ]
