# Generated by Django 5.2 on 2025-05-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_favoritesmockdjango_unique_together_and_more"),
        ("core", "0020_alter_actionstable_action_id_usernotificationqueue_and_more"),
    ]

    operations = []
