# Generated by Django 5.2 on 2025-05-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_usernotificationqueue_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatesmockdjango",
            name="bill_id",
            field=models.ForeignKey(
                db_column="bill_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.billstable",
            ),
        ),
    ]
