# Generated by Django 5.2.1 on 2025-05-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_updatesmockdjango"),
        ("core", "0028_alter_updatesmockdjango_bill_id"),
    ]

    operations = []
