# Generated by Django 5.2 on 2025-05-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_merge_20250523_0205"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostRecentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_upload_date", models.DateField()),
            ],
            options={
                "db_table": "most_recent_upload",
                "managed": False,
            },
        ),
    ]
