# Generated by Django 5.2 on 2025-05-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_mostrecentupload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mostrecentupload",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usernotificationqueue",
            options={},
        ),
    ]
