name: Lint and Commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Python and Node.js
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          node-version: "14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          npm install --save-dev prettier

      - name: Run Prettier
        run: npx prettier --check --write .

      - name: Run Ruff format
        run: ruff format

      - name: Run Ruff check
        run: ruff check --fix

      - name: Commit Ruff + prettier fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting fixes
